---
- include: usage.yml
  when:
   - type is undefined
   - env is undefined
   - core is undefined
   - plugin is undefined
   - web is undefined
   - adaptor is undefined
   - client is undefined
   - link is undefined
   - file is undefined
   - days is undefined

- set_fact:
   var1: 1
  when: type is defined
  ignore_errors: yes

- set_fact:
   var1: 0
  when: type is undefined
  ignore_errors: yes
  
- set_fact:
   var2: 1
  when: env is defined
  ignore_errors: yes
  
- set_fact:
   var2: 0
  when: env is undefined
  ignore_errors: yes
  
- set_fact:
   var3: 1
  when: core is defined
  ignore_errors: yes
  
- set_fact:
   var3: 0
  when: core is undefined
  ignore_errors: yes

- set_fact:
   var4: 1
  when: plugin is defined
  ignore_errors: yes
  
- set_fact:
   var4: 0
  when: plugin is undefined
  ignore_errors: yes

- set_fact:
   var5: 1
  when: web is defined
  ignore_errors: yes
  
- set_fact:
   var5: 0
  when: web is undefined
  ignore_errors: yes

- set_fact:
   var6: 1
  when: adaptor is defined
  ignore_errors: yes
  
- set_fact:
   var6: 0
  when: adaptor is undefined
  ignore_errors: yes
  
- set_fact:
   var7: 1
  when: client is defined
  ignore_errors: yes
  
- set_fact:
   var7: 0
  when: client is undefined
  ignore_errors: yes

- set_fact:
   var8: 1
  when: link is defined
  ignore_errors: yes
  
- set_fact:
   var8: 0
  when: link is undefined
  ignore_errors: yes

- set_fact:
   var9: 1
  when: file is defined
  ignore_errors: yes
  
- set_fact:
   var9: 0
  when: file is undefined
  ignore_errors: yes

- set_fact:
   var10: 1
  when: days is defined
  ignore_errors: yes
  
- set_fact:
   var10: 0
  when: days is undefined
  ignore_errors: yes
  
- shell:  expr {{ var1 }} + {{ var2 }} + {{ var3 }} + {{ var4 }} + {{ var5 }} + {{ var6 }} + {{ var7 }} + {{ var8 }} + {{ var9 }} + {{ var10 }}
  register: allsum

- debug:
    msg: "the total parameter is {{ allsum.stdout }}"
